# Generated by Django 5.2 on 2025-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="title",
            field=models.CharField(default="abc", max_length=255),
        ),
    ]
