# Generated by Django 5.2 on 2025-04-12 15:43

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-Time"),
                            ("PT", "Part-Time"),
                            ("VS", "Visiting"),
                            ("AJ", "Adjunct"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "staff_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("joined_date", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("webauthn_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PR", "Present"),
                            ("AB", "Absent"),
                            ("LT", "Late"),
                            ("EX", "Excused"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="management.lecturer",
                    ),
                ),
            ],
        ),
    ]
