# Generated by Django 5.2 on 2025-04-12 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("STD", "Student"),
                            ("PAR", "Parent"),
                            ("VND", "Vendor"),
                            ("GST", "Guest"),
                        ],
                        default="GST",
                        max_length=3,
                    ),
                ),
                (
                    "whom_to_meet",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purpose", models.TextField()),
                ("photo", models.ImageField(upload_to="visitor_photos/")),
                (
                    "id_proof",
                    models.FileField(blank=True, null=True, upload_to="visitor_ids/"),
                ),
                ("check_in", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("denial_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "visitors",
                "ordering": ["-check_in"],
            },
        ),
    ]
