# Generated by Django 5.2 on 2025-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="duration",
            field=models.CharField(default="1 HOUR", max_length=100),
        ),
    ]
